templateDir: aem

files:

# Define a AEM content package containing OSGi configurations from a Sling Provisioning file
- file: sling-provisioning.provisioning
  dir: packages
  template: sling-provisioning.provisioning.hbs
  validators:
  - sling-provisioning
  # Post-processors apply further actions after generation the file
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackageGroup: sample
    contentPackageName: config-sample
    contentPackageDescription: The description of the sample package.
    contentPackageVersion: "${version}"
    contentPackageRootPath: /apps/sample/config


# Define a AEM content package with some JCR content (Sling Mapping Example)
- file: sling-mapping.json
  dir: packages
  template: sling-mapping.json.hbs
  # Post-processors apply further actions after generation the file
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackageGroup: sample
    contentPackageName: mapping-sample
    contentPackageRootPath: /etc/map/http
    contentPackageFilters:
    - filter: /etc/map/http
      rules:
      - rule: exclude
        pattern: /etc/map/http
      - rule: include
        pattern: /etc/map/http/.*
      - rule: exclude
        pattern: /etc/map/http/AppMeasurementBridge


# Defines configuration parameters and default values
config:

  jvm:
    path: /path/to/java
    heapspace:
      min: 512m
      max: 2048m
    permgenspace:
      max: 256m

  var1: Value 1
